const colorHex = {
    darkText: "#444",
    lightest: "#F1EBE7",
    lightText: "#757575",
    gray: "#888888",
    lightGray: "#E2E2E2",
    lightestGreen: "#D6E4E6",
    lightGreen: "#B9EFE9",
    green: "#33CCAB",
    darkGreen: "#29A389",
    darkerGreen: "#0B6E79",
    darkestGreen: "#07454c",
    lightPink: "#FFCCD8",
    darkPink: "#FDBCA3",
    darkestPink: "#7A3814",
    yellow: "#F9EB91",
    darkYellow: "#F4DD48",
    darkestYellow: "#F4DD48",
    white: "#ffffff",
    lightBlue: "#e6f9f7",
    red: "#cc3333",
    twitter: "#1da1f2",
    facebook: "#3b5998",
    beige: "#F0ECEA",
    magenta: "#CC33A1",
    lightRoyal: "#BAD0FF",
    royal: "#6590ED",
    turquoise: "#0DADB1",
    indigo: "#294FA3",
    dolphin: "#47445E",
    mediumDolphin: "#8D8BA1",
    lightDolphin: "#D3D1E3",
    coral: "#FF7866",
    pink: "#FF99B2",
    teal: "#00cee5",
    bgGreen: "#F2F6F7",
    bgDolphin: "#F6F6F9",
}

export const Colors = {
    ...colorHex,
    bgLight: colorHex.lightest,
    bgDefault: colorHex.white,
    textDefault: colorHex.darkestGreen,
    borderLight: colorHex.gray,
}

export interface GradientPoint {
    offset: string,
    color: string,
}