export enum QueryParam {
    SENT_TO_EMAIL_ADDRESS = "ref",
    REFERRED_BY_EMAIL = "ref",
    SUBSCRIPTION_PLAN = "p",
    IS_PRE_ORDER = "preorder",
    MAILCHIMP_EMAIL_ID = "mcuid",
    PURCHASE_AMOUNT = "amount",
    PURCHASE_ITEM_ID = 'productId',
    EMAIL = 'e',
    REDIRECT_URL = 'signInSuccessUrl',
    MODE = "mode",
    OOB_CODE = "oobCode",
    API_KEY= "apiKey",
    CONTINUE_URL = "continueUrl",
    LANG = "lang",
    CONTENT_INDEX="slide",
    MESSAGE="message",
    PROMPT_CONTENT_ENTRY_ID="pceid",

}