# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@3.2.0 #https://github.com/CircleCI-Public/slack-orb

executors:
  cactus-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15.3-browsers
aliases:
  ## Module Names
  - &root-module ""
  - &web-module "web"
  - &functions-module "functions"
  - &shared-module "shared"
  - &scripts-module "scripts"
  - &admin-module "shared-admin"

  ## Slack Configs
  - &webhook-engineering-ci
    webhook: "https://hooks.slack.com/services/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"

  - &notify-job-started-slack
    <<: *webhook-engineering-ci
    color: '#42e2f4'
    message: "Job \\`$CIRCLE_JOB\\` starting on branch *$CIRCLE_BRANCH* <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|Workflow>"


commands:
  get-repo-link:
    steps:
      - run:
          name: Get Repo Link
          command: |
            SLACK_GIT_LINK="<https://github.com/Kinecho/cactus/compare/${CIRCLE_BRANCH}?expand=1|Open Pull Request>"
            if [[ ! -z $CIRCLE_PULL_REQUEST ]] ; then
              SLACK_GIT_LINK="<$CIRCLE_PULL_REQUEST|View Pull Request>"
            fi
            echo "Slack GIT Link is \"${SLACK_GIT_LINK}\""
            export SLACK_GIT_LINK
            echo $SLACK_GIT_LINK >> .slack_git_url.txt
            echo 'export SLACK_GIT_LINK="$SLACK_GIT_LINK"' >> $BASH_ENV
  restore-module:
    parameters:
      module:
        type: enum
        default: *root-module
        enum: [*root-module, *web-module, *functions-module, *shared-module, *scripts-module, *admin-module]
        description: "The module name, e.g. web, functions, etc"
    steps:
      - when:
          condition: << parameters.module >>
          steps:
            - restore_cache:
                name: "Restore << parameters.module >> Cache"
                keys:
                  - v4-<< parameters.module >>-dependency-{{ .Branch }}-{{ checksum "<< parameters.module >>/package.json" }}
                  - v4-<< parameters.module >>-dependency-{{ .Branch }}-
                  - v4-<< parameters.module >>-dependency-
      - unless:
          condition: << parameters.module >>
          steps:
            - restore_cache:
                name: "Save Root Dependencies to Cache"
                keys:
                  - v4-root-dependency-{{ .Branch }}-{{ checksum "package.json" }}
                  - v4-root-dependency-{{ .Branch }}-
                  - v4-root-dependency-
  restore-all:
    steps:
      - restore-module:
          module: *root-module
      - restore-module:
          module: *web-module
      - restore-module:
          module: *shared-module
      - restore-module:
          module: *functions-module
      - restore-module:
          module: *scripts-module
      - restore-module:
          module: *admin-module

  install-module:
    parameters:
      module:
        type: enum
        enum: [*root-module, *web-module, *functions-module, *shared-module, *scripts-module, *admin-module]
        default: *root-module
        description: "The module name, e.g. web, functions, etc"
    steps:
      - restore-module:
          module: << parameters.module >>
      - when:
          condition: << parameters.module >>
          steps:
            - run: npm --prefix << parameters.module >> install
            - save_cache:
                name: "Save << parameters.module >> Dependencies to Cache"
                paths:
                  - << parameters.module >>/node_modules
                key: v4-<< parameters.module >>-dependency-{{ .Branch }}-{{ checksum "<< parameters.module >>/package.json" }}
      - unless:
          condition: << parameters.module >>
          steps:
            - run: npm install
            - save_cache:
                name: "Save Root Dependencies to Cache"
                paths:
                  - node_modules
                key: v4-root-dependency-{{ .Branch }}-{{ checksum "package.json" }}
  notify-on-failure:
    parameters:
      workflow_name:
        type: string
        default: "<not set>"
        description: "The message to send to slack"
    steps:
      - get-repo-link
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true
          include_project_field: false
          include_job_number_field: false
          failure_message: ":boom: *$CIRCLE_JOB* job failed in a <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID| CI workflow >\nBranch \\`<https://github.com/Kinecho/cactus-ios/compare/${CIRCLE_BRANCH}|${CIRCLE_BRANCH}>\\`"

jobs:
  get-changes:
    executor: cactus-web
    resource_class: small
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: . git-folder.sh
      - run: ls -a | grep modules_to_deploy.txt
      - run:
          name: "Determine Modules to Deploy"
          command: |
            echo "Printing output & copying file"
            cat modules_to_deploy.txt
            cp modules_to_deploy.txt workspace
      - persist_to_workspace:
          root: "workspace"
          paths:
            - modules_to_deploy.txt
  deploy-stage:
    executor: cactus-web
    resource_class: large
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run:
          name: "Deploy to Modules Firebase"
          no_output_timeout: 20m
          command: |
            echo "The current build output is"
            echo "Deploy Modules: $(cat /tmp/workspace/modules_to_deploy.txt)"
            MODULES=$(cat /tmp/workspace/modules_to_deploy.txt || "NONE")

            if [[ `cat /tmp/workspace/modules_to_deploy.txt` == "NONE" ]]; then
              echo "Nothing to Deploy";
              exit 0
            else
              echo "Starting firebase deploy for --only ${MODULES}"
              firebase deploy --only $MODULES -P stage
            fi
      - notify-on-failure
  install-all:
    executor: cactus-web
    resource_class: small
    steps:
      - checkout
      - install-module:
          module: *root-module
      - install-module:
          module: *functions-module
      - install-module:
          module: *web-module
      - install-module:
          module: *shared-module
      - install-module:
          module: *scripts-module
      - install-module:
          module: *admin-module
      - notify-on-failure
  test-web:
    executor: cactus-web
    resource_class: small
    steps:
      - checkout
      - restore-module:
          module: web
      - restore-module:
          module: shared
      - run:
          name: "TSLint"
          command: npm --prefix web run lint:ci
      - run:
          name: "Compile TypeScript"
          command: npm --prefix web run tsc
      - run:
          name: "Run Unit Tests"
          command: npm --prefix web run test:ci
      - store_test_results:
          path: web/reports/tests
      - store_test_results:
          path: web/reports/coverage
      - store_artifacts:
          path: web/reports
      - notify-on-failure
  test-functions:
    executor: cactus-web
    resource_class: small
    steps:
      - checkout
      - restore-module:
          module: *functions-module
      - restore-module:
          module: *shared-module
      - restore-module:
          module: *admin-module
      - run:
          name: "TSLint"
          command: npm --prefix functions run lint:ci
      - run:
          name: "Build Sources"
          command: npm --prefix functions run build
      - run:
          name: "Run Unit Tests"
          command: npm --prefix functions run test:ci
      - store_test_results:
          path: functions/reports/tests
      - store_test_results:
          path: functions/reports/coverage
      - store_artifacts:
          path: functions/reports
      - notify-on-failure

  test-shared:
    executor: cactus-web
    resource_class: small
    steps:
      - checkout
      - restore-module:
          module: shared
      - run:
          name: "TSLint"
          command: npm --prefix shared run lint:ci
      - run:
          name: "Run Unit Tests"
          command: npm --prefix shared run test:ci
      - store_test_results:
          path: shared/reports/tests
      - store_test_results:
          path: shared/reports/coverage
      - store_artifacts:
          path: shared/reports
      - notify-on-failure
  test-scripts:
    executor: cactus-web
    resource_class: small
    steps:
      - checkout
      - restore-module:
          module: shared
      - restore-module:
          module: scripts
      - restore-module:
          module: *admin-module
      - run:
          name: "TSLint"
          command: npm --prefix scripts run lint:ci
      - run:
          name: "Run Unit Tests"
          command: npm --prefix scripts run test:ci
      - store_test_results:
          path: scripts/reports/tests
      - store_artifacts:
          path: scripts/reports
      - notify-on-failure
  ready-for-deploy:
    executor: cactus-web
    resource_class: small
    steps:
      - run: echo "Ready for deployments"
      - slack/notify:
          <<: *webhook-engineering-ci
          color: 'good'
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          message: "A Stage Build is <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|ready for promotion>"
  prod-deploy-started:
    executor: cactus-web
    resource_class: small
    steps:
      - run: echo "Notify prod deploy started"
      - slack/notify:
          <<: *webhook-engineering-ci
          color: 'good'
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          message: "$CIRCLE_USERNAME has promoted a Stage Build. <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|View Workflow>"
  branch-deploy-started:
    executor: cactus-web
    resource_class: small
    steps:
      - run: echo "Notify Feature Branch deploy started"
      - slack/notify:
          <<: *webhook-engineering-ci
          color: 'good'
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          message: "$CIRCLE_USERNAME has started deploying \\`${CIRCLE_BRANCH}\\` to stage. <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|View Workflow>"

  branch-deploy-finished:
    executor: cactus-web
    resource_class: small
    steps:
      - run: echo "Notify Feature Branch deploy finished"
      - slack/notify:
          <<: *webhook-engineering-ci
          color: 'good'
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          message: "`$CIRCLE_BRANCH` has been deployed to stage.\n<https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|View Workflow> | $(cat .slack_git_url.txt)"


  firebase-deploy:
    description: "Deploy selected modules to the selected project"
    parameters: # see https://circleci.com/docs/2.0/reusing-config/#parameter-types
      project:
        type: enum
        description: The project alias to deploy. Either "stage" or "prod"
        default: "stage"
        enum: ["stage", "prod"]
      modules:
        type: string
        default: "error"
        description: The firebase modules to deploy. Example "hosting" or "functions" or "functions:test,functions:slack"
    executor: cactus-web
    resource_class: large
    steps:
      - checkout
      - restore-all
      - run:
          no_output_timeout: 20m
          name: Deploy to Firebase
          command: |
            git config --global user.name CircleCI
            echo "Setting default project to be << parameters.project >>"
            npx firebase use << parameters.project >>
            echo "Starting firebase deploy for << parameters.modules >> on project << parameters.project >>"
            npx firebase deploy -P << parameters.project >> -f
      - notify-on-failure
  notify-workflow-finished:
    description: "Notify slack that a workflow has finished and provide a link"
    parameters:
      workflow_name:
        type: string
        default: "DEFAULT"
        description: "The message to send to slack"
    executor: cactus-web
    resource_class: small
    steps:
      - slack/notify:
          <<: *webhook-engineering-ci
          color: "good"
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          message: ":white_check_mark: Finished Workflow <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID| << parameters.workflow_name >> > \nBranch \\`${CIRCLE_BRANCH}\\`"
  notify-workflow-started:
    description: "Notify slack that a workflow has started and provide a link"
    resource_class: small
    parameters:
      workflow_name:
        type: string
        default: "DEFAULT"
        description: "The message to send to slack"
    executor: cactus-web
    steps:
      - slack/notify:
          <<: *webhook-engineering-ci
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          color: "#d8d8d8"
          message: "Starting workflow <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID| << parameters.workflow_name >> > \nBranch \\`${CIRCLE_BRANCH}\\`"
  notify-branch-workflow-started:
    description: "Notify slack that a branch workflow has started and provide a link"
    resource_class: small
    parameters:
      workflow_name:
        type: string
        default: "DEFAULT"
        description: "The message to send to slack"
    executor: cactus-web
    steps:
      - get-repo-link
      - slack/notify:
          <<: *webhook-engineering-ci
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          color: "#d8d8d8"
          ts: "$(date +%s)"
          message: ":building_construction: Starting workflow <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID| << parameters.workflow_name >> > \nBranch \\`${CIRCLE_BRANCH}\\`\n$(cat .slack_git_url.txt)"
  notify-branch-workflow-finished:
    description: "Notify slack that a branch workflow has finished and provide a link"
    parameters:
      workflow_name:
        type: string
        default: "DEFAULT"
        description: "The message to send to slack"
    executor: cactus-web
    resource_class: small
    steps:
      - get-repo-link
      - slack/notify:
          <<: *webhook-engineering-ci
          color: "good"
          include_job_number_field: false
          include_visit_job_action: false
          include_project_field: false
          ts: "$(date +%s)"
          message: ":white_check_mark: \\`${CIRCLE_BRANCH}\\` <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID| << parameters.workflow_name >> > completed successfully.\n$(cat .slack_git_url.txt)"

workflows:
  version: 2.1
  branch_build_and_test:
    jobs:
      - notify-branch-workflow-started:
          name: &workflow_name Feature Branch Build & Test
          workflow_name: *workflow_name
          filters:
            branches:
              ignore: master
      - install-all:
          name: &install_all_name "Install Dependencies"
          requires:
            - *workflow_name
          filters:
            branches:
              ignore: master
      - test-shared:
          name: &test_shared_name "Shared Tests"
          filters:
            branches:
              ignore: master
          requires:
            - *install_all_name
      - test-scripts:
          name: &test_scripts_name "Scripts Tests"
          filters:
            branches:
              ignore: master
          requires:
            - *install_all_name
      - test-web:
          name: &test_web_name "Web Tests"
          filters:
            branches:
              ignore: master
          requires:
            - *install_all_name
      - test-functions:
          name: &test_functions_name "API Tests"
          filters:
            branches:
              ignore: master
          requires:
            - *install_all_name
      - notify-branch-workflow-finished:
          name: &all_tests_finished "Notify Tests Passed"
          workflow_name: "Feature Branch Tests"
          requires:
            - *install_all_name
            - *test_functions_name
            - *test_scripts_name
            - *test_shared_name
            - *test_web_name
          filters:
            branches:
              ignore: master
      - branch_deploy_approval:
          type: approval
          name: &stage_approval_name "Deploy To Stage Approval"
          requires:
            - *all_tests_finished
      - branch-deploy-started:
          name: "Notify Branch Deploy Started"
          requires:
            - *stage_approval_name
      - firebase-deploy:
          name: &branch_deploy_name "Deploy Branch to Stage"
          project: "stage"
          requires:
            - *stage_approval_name
      - branch-deploy-finished:
            name: "Notify Branch Deploy Finished"
            requires:
              - *branch_deploy_name
              - *stage_approval_name


  cactus_release_pipeline:
    jobs:
      - notify-workflow-started:
          name: &workflow_name Cactus Release Pipeline
          workflow_name: *workflow_name
          filters:
            branches:
              only: master
      - install-all:
          name: &install_all_name "Install Dependencies"
          filters:
            branches:
              only: master
      - test-shared:
          name: &test_shared_name "Shared Tests"
          filters:
            branches:
              only: master
          requires:
            - *install_all_name
      - test-scripts:
          name: &test_scripts_name "Scripts Tests"
          requires:
            - *install_all_name
      - test-web:
          name: &test_web_name "Web Tests"
          requires:
            - *install_all_name
      - test-functions:
          name: &test_functions_name "API Tests"
          requires:
            - *install_all_name
      - firebase-deploy:
          name: &deploy_stage_name "Stage: Deploy All"
          modules: "functions,hosting"
          project: "stage"
          requires:
            - *install_all_name
            - *test_web_name
            - *test_shared_name
            - *test_functions_name
            - *test_scripts_name
      - ready-for-deploy:
          name: "Notify Promotion Ready"
          requires:
            - *deploy_stage_name
      - prod_deploy_approval:
          type: approval
          name: &prod_approval_name "Deploy To Prod Approval"
          requires:
            - *deploy_stage_name
      - prod-deploy-started:
          name: "Notify Promotion"
          requires:
              - *prod_approval_name
      - firebase-deploy:
          name: "Prod: Deploy All"
          project: "prod"
          requires:
            - *prod_approval_name
