# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@3.2.0 #https://github.com/CircleCI-Public/slack-orb

aliases:
  - &web-dependency-key
    key: web-dependency-{{ .Branch }}-{{ checksum "web/package.json" }}
  - &web-dependency-keys
    keys:
      - web-dependency-{{ .Branch }}-{{ checksum "web/package.json" }}
      - web-dependency-{{ .Branch }}-
      - web-dependency-
  - &restore-web-dependencies
    name: Restore Web Dependency Cache
    <<: *web-dependency-keys
  - &webhook-engineering-ci
    webhook: "https://hooks.slack.com/services/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"

jobs:
  install-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - slack/notify: #see https://github.com/CircleCI-Public/slack-orb
          <<: *webhook-engineering-ci
          color: '#42e2f4'
          message: "Starting `install-web` for *Cactus Web*"
      #          webhook: https://hooks.slack.com/services/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 #this is engineering-ci

      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-web-dependencies

      - run: npm --prefix web install

      - save_cache:
          name: "Save Web Dependencies"
          paths:
            - web/node_modules
          <<: *web-dependency-key

      #notify slack of the status. this must be the last step in the job
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: false # Optional: if set to `true` then only failure messages will occur.
  test-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - slack/notify: #see https://github.com/CircleCI-Public/slack-orb
          <<: *webhook-engineering-ci
          color: '#42e2f4'
          message: "Starting test-web for *Cactus Web*"

      - checkout
      - restore_cache: *restore-web-dependencies
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm --prefix web test

      #notify slack of the status. this must be the last step in the job
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: false # Optional: if set to `true` then only failure messages will occur.

workflows:
  version: 2.1
  web_build_and_test:
    jobs:
      - install-web
      - test-web:
          requires:
            - install-web