# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@3.2.0 #https://github.com/CircleCI-Public/slack-orb


aliases:
  ## WEB CACHES
  - &web-dependency-key
    key: web-dependency-{{ .Branch }}-{{ checksum "web/package.json" }}
  - &web-dependency-keys
    keys:
      - web-dependency-{{ .Branch }}-{{ checksum "web/package.json" }}
      - web-dependency-{{ .Branch }}-
      - web-dependency-
  - &restore-web-dependencies
    name: Restore Web Dependency Cache
    <<: *web-dependency-keys

  ## SHARED CACHES
  - &shared-dependency-key
    key: shared-dependency-{{ .Branch }}-{{ checksum "shared/package.json" }}
  - &shared-dependency-keys
    keys:
      - shared-dependency-{{ .Branch }}-{{ checksum "shared/package.json" }}
      - shared-dependency-{{ .Branch }}-
      - shared-dependency-
  - &restore-shared-dependencies
    name: Restore Shared Dependency Cache
    <<: *shared-dependency-keys

  ## Slack Configs
  - &webhook-engineering-ci
    webhook: "https://hooks.slack.com/services/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"

  - &notify-job-started-slack
    <<: *webhook-engineering-ci
    color: '#42e2f4'
    message: "Job \\`$CIRCLE_JOB\\` starting on branch *$CIRCLE_BRANCH* <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|Workflow>"

jobs:
  install-shared:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - slack/notify: *notify-job-started-slack

      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-shared-dependencies

      - run: npm --prefix shared install

      - save_cache:
          name: "Save Shared Dependencies to Cache"
          paths:
            - shared/node_modules
          <<: *shared-dependency-key

      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  install-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - slack/notify: *notify-job-started-slack

      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-web-dependencies

      - run: npm --prefix web install

      - save_cache:
          name: "Save Web Dependencies to Cache"
          paths:
            - web/node_modules
          <<: *web-dependency-key

      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true
  test-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-web-dependencies
      - restore_cache: *restore-shared-dependencies
      - run:
          name: "Run Unit Tests"
          command: npm --prefix web test
      - run:
          name: "Compile TypeScript"
          command: npm --prefix web run tsc
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

workflows:
  version: 2.1
  web_build_and_test:
    jobs:
      - install-shared:
          name: &shared_install_name "Install Dependencies Shared"
      - install-web:
          name: &web_install_name "Install Dependencies Web"
      - test-web:
          requires:
            - *shared_install_name
            - *web_install_name