# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@3.2.0 #https://github.com/CircleCI-Public/slack-orb

executors:
  cactus-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.15.0-browsers


aliases:
  ## WEB CACHES
  - &web-dependency-key
    key: web-dependency-{{ .Branch }}-{{ checksum "web/package.json" }}
  - &web-dependency-keys
    keys:
      - web-dependency-{{ .Branch }}-{{ checksum "web/package.json" }}
      - web-dependency-{{ .Branch }}-
      - web-dependency-
  - &restore-web-dependencies
    name: Restore Web Dependency Cache
    <<: *web-dependency-keys

  ## SHARED CACHES
  - &shared-dependency-key
    key: v2-shared-dependency-{{ .Branch }}-{{ checksum "shared/package.json" }}
  - &shared-dependency-keys
    keys:
      - v2-shared-dependency-{{ .Branch }}-{{ checksum "shared/package.json" }}
      - v2-shared-dependency-{{ .Branch }}-
      - v2-shared-dependency-
  - &restore-shared-dependencies
    name: Restore Shared Dependency Cache
    <<: *shared-dependency-keys

  ## FUNCTIONS CACHES
  - &functions-dependency-key
    key: functions-dependency-{{ .Branch }}-{{ checksum "functions/package.json" }}
  - &functions-dependency-keys
    keys:
      - functions-dependency-{{ .Branch }}-{{ checksum "functions/package.json" }}
      - functions-dependency-{{ .Branch }}-
      - functions-dependency-
  - &restore-functions-dependencies
    name: Restore Functions Dependency Cache
    <<: *functions-dependency-keys

  ## SCRIPTS CACHES
  - &scripts-dependency-key
    key: scripts-dependency-{{ .Branch }}-{{ checksum "scripts/package.json" }}
  - &scripts-dependency-keys
    keys:
      - scripts-dependency-{{ .Branch }}-{{ checksum "scripts/package.json" }}
      - scripts-dependency-{{ .Branch }}-
      - scripts-dependency-
  - &restore-scripts-dependencies
    name: Restore Scripts Dependency Cache
    <<: *scripts-dependency-keys


  ## ROOT CACHES
  - &root-dependency-key
    key: v2-root-dependency-{{ .Branch }}-{{ checksum "package.json" }}
  - &root-dependency-keys
    keys:
      - v2-root-dependency-{{ .Branch }}-{{ checksum "package.json" }}
      - v2-root-dependency-{{ .Branch }}-
      - v2-root-dependency-
  - &restore-root-dependencies
    name: Restore Root Dependency Cache
    <<: *root-dependency-keys


  ## Slack Configs
  - &webhook-engineering-ci
    webhook: "https://hooks.slack.com/services/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"

  - &notify-job-started-slack
    <<: *webhook-engineering-ci
    color: '#42e2f4'
    message: "Job \\`$CIRCLE_JOB\\` starting on branch *$CIRCLE_BRANCH* <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|Workflow>"

jobs:
  get-changes:
    executor: cactus-web
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: . git-folder.sh
      - run: ls -a | grep modules_to_deploy.txt
      - run:
          name: "Determine Modules to Deploy"
          command: |
            echo "Printing output & copying file"
            cat modules_to_deploy.txt
            cp modules_to_deploy.txt workspace
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: "workspace"
          # Must be relative path from root
          paths:
            - modules_to_deploy.txt


  deploy-stage:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run:
          name: "Deploy to Modules Firebase"
          command: |
            echo "The current build output is"
            echo "Deploy Modules: $(cat /tmp/workspace/modules_to_deploy.txt)"
            MODULES=$(cat /tmp/workspace/modules_to_deploy.txt || "NONE")

            if [[ `cat /tmp/workspace/modules_to_deploy.txt` == "NONE" ]]; then
              echo "Nothing to Deploy";
              exit 0
            else
              echo "Starting firebase deploy for --only ${MODULES}"
              firebase deploy --only $MODULES -P stage
            fi
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  install-functions:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-functions-dependencies
      - run: npm --prefix functions install
      - save_cache:
          name: "Save Functions Dependencies to Cache"
          paths:
            - functions/node_modules
          <<: *functions-dependency-key

      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  install-shared:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-shared-dependencies
      - run: npm --prefix shared install
      - save_cache:
          name: "Save Shared Dependencies to Cache"
          paths:
            - shared/node_modules
          <<: *shared-dependency-key
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true
  install-scripts:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-shared-dependencies
      - run: npm --prefix scripts install
      - save_cache:
          name: "Save Scripts Dependencies to Cache"
          paths:
            - scripts/node_modules
          <<: *scripts-dependency-key
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  install-root:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      # Download and cache dependencies
      - restore_cache: *restore-root-dependencies
      - run: npm install
      - run:
          name: "Verify firebase is available"
          command: npx firebase --version
      - save_cache:
          name: "Save Root Dependencies to Cache"
          paths:
            - node_modules
          <<: *root-dependency-key
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  install-web:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack

      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-web-dependencies

      - run: npm --prefix web install

      - save_cache:
          name: "Save Web Dependencies to Cache"
          paths:
            - web/node_modules
          <<: *web-dependency-key

      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  test-web:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-web-dependencies
      - restore_cache: *restore-shared-dependencies
      - run:
          name: "TSLint"
          command: npm --prefix web run lint:ci
      - run:
          name: "Compile TypeScript"
          command: npm --prefix web run tsc
      - run:
          name: "Run Unit Tests"
          command: npm --prefix web run test:ci
      - store_test_results:
          path: web/reports/tests
      - store_test_results:
          path: web/reports/coverage
      - store_artifacts:
          path: web/reports
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true
  test-functions:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-functions-dependencies
      - restore_cache: *restore-shared-dependencies
      - run:
          name: "TSLint"
          command: npm --prefix functions run lint:ci
      - run:
          name: "Build Sources"
          command: npm --prefix functions run build
      - run:
          name: "Run Unit Tests"
          command: npm --prefix functions run test:ci
      - store_test_results:
          path: functions/reports/tests
      - store_test_results:
          path: functions/reports/coverage
      - store_artifacts:
          path: functions/reports
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true

  test-shared:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-shared-dependencies
      - run:
          name: "TSLint"
          command: npm --prefix shared run lint:ci
      - run:
          name: "Run Unit Tests"
          command: npm --prefix shared run test:ci
      - store_test_results:
          path: shared/reports/tests
      - store_test_results:
          path: shared/reports/coverage
      - store_artifacts:
          path: shared/reports
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true
  test-scripts:
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-shared-dependencies
      - restore_cache: *restore-scripts-dependencies
      - run:
          name: "TSLint"
          command: npm --prefix scripts run lint:ci
      - run:
          name: "Run Unit Tests"
          command: npm --prefix scripts run test:ci
      - store_test_results:
          path: scripts/reports/tests
      - store_artifacts:
          path: scripts/reports
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: true
  ready-for-deploy:
    executor: cactus-web
    steps:
      - run: echo "Ready for deployments"
      - slack/notify:
          <<: *webhook-engineering-ci
          color: 'good'
          message: "Stage Deployment Jobs are now Available. Go to the <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|workflow here>"

  firebase-deploy:
    description: "Deploy selected modules to the selected project"
    parameters: # see https://circleci.com/docs/2.0/reusing-config/#parameter-types
      project:
        type: enum
        description: The project alias to deploy. Either "stage" or "prod"
        default: "stage"
        enum: ["stage", "prod"]
      modules:
        type: string
        default: "error"
        description: The firebase modules to deploy. Example "hosting" or "functions" or "functions:test,functions:slack"
    executor: cactus-web
    steps:
      - slack/notify: *notify-job-started-slack
      - checkout
      - restore_cache: *restore-root-dependencies
      - restore_cache: *restore-shared-dependencies
      - restore_cache: *restore-web-dependencies
      - restore_cache: *restore-functions-dependencies
      - restore_cache: *restore-scripts-dependencies
      - run:
          name: Deploy to Firebase
          command: |
            echo "Setting default project to be << parameters.project >>"
            npx firebase use << parameters.project >>
            echo "Starting firebase deploy for << parameters.modules >> on project << parameters.project >>"
            npx firebase deploy --only << parameters.modules >> -P << parameters.project >>
      - slack/status:
          <<: *webhook-engineering-ci
          fail_only: false
  notify-workflow-started:
    description: "Notify slack that a workflow has started and provide a link"
    parameters:
      workflow_name:
        type: string
        default: "DEFAULT"
        description: "The message to send to slack"
    executor: cactus-web
    steps:
      - slack/notify:
          <<: *webhook-engineering-ci
          message: "Starting <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|workflow << parameters.workflow_name >> >"

workflows:
  version: 2.1
  cactus_release_pipeline:
    jobs:
      - notify-workflow-started:
          name: &workflow_name Cactus Release Pipeline
          workflow_name: *workflow_name
      - install-root:
          name: &root_install_name "Root: Install Dependencies"
      - get-changes:
          name: &get_changes_name "Get module changes"
          requires:
            - *root_install_name
      - install-shared:
          name: &shared_install_name "Shared: Install Dependencies"
          requires:
            - *get_changes_name
      - install-scripts:
          name: &scripts_install_name "Scripts: Install Dependencies"
          requires:
            - *get_changes_name
      - install-web:
          name: &web_install_name "Web: Install Dependencies"
          requires:
            - *get_changes_name
      - install-functions:
          name: &functions_install_name "Functions: Install Dependencies"
          requires:
            - *get_changes_name
      - test-shared:
          name: &test_shared_name "Shared Tests"
          requires:
            - *root_install_name
            - *shared_install_name
      - test-scripts:
          name: &test_scripts_name "Scripts Tests"
          requires:
            - *root_install_name
            - *shared_install_name
            - *scripts_install_name
      - test-web:
          name: &test_web_name "Web Tests"
          requires:
            - *shared_install_name
            - *root_install_name
            - *web_install_name
      - test-functions:
          name: &test_functions_name "API Tests"
          requires:
            - *root_install_name
            - *shared_install_name
            - *functions_install_name
      - ready-for-deploy:
          name: &ready_for_deploy_name "Ready for Deployments"
          requires:
            - *scripts_install_name
            - *root_install_name
            - *test_web_name
            - *test_shared_name
            - *shared_install_name
            - *test_functions_name
            - *functions_install_name
            - *test_scripts_name
            - *web_install_name
            - *get_changes_name

      # WEB Stage Deploy
      - stage-web-approval:
          name: &deploy_stage_web_approval "Deploy Web to Stage"
          type: approval
          requires:
            - *ready_for_deploy_name
      - firebase-deploy:
          name: &deploy_stage_web_name "Stage: Deploy Web"
          modules: "hosting"
          project: "stage"
          requires:
            - *ready_for_deploy_name
            - *deploy_stage_web_approval

      # FUNCTIONS Stage Deploy
      - stage-functions-approval:
          name: &deploy_stage_api_approval "Deploy API to Stage"
          type: approval
          requires:
            - *ready_for_deploy_name
      - firebase-deploy:
          name: &deploy_stage_api_name "Stage: Deploy API"
          modules: "functions"
          project: "stage"
          requires:
            - *ready_for_deploy_name
            - *deploy_stage_api_approval

      # ALL Stage Deploy
      - stage-deploy-all-approval:
          name: &deploy_stage_all_approval "Deploy All to Stage"
          type: approval
          requires:
            - *ready_for_deploy_name
      - firebase-deploy:
          name: &deploy_stage_api_name "Stage: Deploy All"
          modules: "functions,hosting"
          project: "stage"
          requires:
            - *ready_for_deploy_name
            - *deploy_stage_all_approval

