export enum PageRoute {
    SIGNUP = "/signup",
    LOGIN = "/login",
    HOME = "/",
    SIGNUP_CONFIRMED = "/confirmed",
    CHECKOUT = "/checkout",
    JOURNAL_HOME = "/home",
    PROMPTS_ROOT = "/prompts",
    FRIENDS = "/friends",
    SHARED_REFLECTION = "/reflection",
    SOCIAL = "/activity",
    ACCOUNT = "/account",
    UNSUBSCRIBE_SUCCESS = "/unsubscribe-confirmed",
    IOS_MAGIC_LINK_LOGIN = "/ios-login-continue",
    PAYMENT_PLANS = "/pricing",
}