export enum PageRoute {
    SIGNUP = "/signup",
    LOGIN = "/login",
    HOME = "/",
    SIGNUP_CONFIRMED = "/confirmed",
    CHECKOUT = "/checkout",
    JOURNAL_HOME = "/home",
    PROMPTS_ROOT = "/prompts",
    FRIENDS = "/friends",
    SHARED_REFLECTION = "/reflection",
    SOCIAL = "/activity",
    SPONSOR = "/sponsor",
    ACCOUNT = "/account",
    UNSUBSCRIBE_SUCCESS = "/unsubscribe-confirmed",
    NATIVE_APP_MAGIC_LINK_LOGIN = "/app-login-continue",
    PRICING = "/pricing",
    CORE_VALUES = "/core-values",
}
